---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(parallel)
library(tidyverse)
library(magrittr)
library(microbenchmark)
```

```{r}
prepare_text <- function(ingrid_values){   ##This function finds out the position of all the brackets and commas
  ##Remove information before ":"
  
  #Need to know whether the braces have any comma in between them
  ##For comma
  comma_list1 <- gregexpr(",", ingrid_values)[[1]]
  names(comma_list1) <- rep(",", length(comma_list1))
  
  ##For open round brackets
  round_openb_list <- gregexpr("\\(", ingrid_values, perl = T)[[1]]
  #round_openb_list <- gregexpr("\\((?=([^\\)]+,))", ingrid_values, perl = T)[[1]] ##Changed 06_17_2020
  names(round_openb_list) <- rep("(", length(round_openb_list))
  
  ##For close round brackets
  round_closeb_list <- gregexpr("\\)", ingrid_values, perl = T)[[1]]
  #closeb_matches <- gregexpr(",[^\\(\\)]+\\){,1}", ingrid_values)[[1]] ##Added 06_17_2020
  #round_closeb_list <- closeb_matches + attr(closeb_matches, which = "match.length") - 1     ##Added 06_17_2020
  names(round_closeb_list) <- rep(")", length(round_closeb_list))
  
  ##appending final list
  brackets <- c(comma_list1, round_openb_list, round_closeb_list, str_length(ingrid_values))
  brackets %<>% sort(decreasing = F)
  brackets <-  brackets[brackets > 0] ##Ensuring that the characters not found are removed from the analysis
  
  
  return(brackets)
  rm(brackets)
}
```


```{r}
func_ingredTransform <- function(text) {
  braces <- c(1,1,1)
  names(braces) <- c("(", "{", "[")
  neg_braces <- c(-1, -1, -1)
  names(neg_braces) <- c(")", "}", "]")
  text <- gsub("\\{|\\[", replacement = "(", text)
  text <- gsub("\\}|\\]", replacement = ")", text)
  #text <- gsub(pattern = ", \\(", replacement = " \\(", text)
  #text <- gsub(pattern = ",\\(", replacement = " \\(", text)
  text <- gsub("\\*|\\*\\*", "", text)
  text <- gsub("\\+|\\+\\+", "", text)
  
  # for (ing_repl in 1:nrow(ingred_replacements)) {
  #   #browser()
  #   #print(without_brackets)
  #   text <- gsub(
  #     pattern = ingred_replacements$Ingredient[ing_repl],
  #     replacement = ingred_replacements$Replacement[ing_repl],
  #     text,
  #     ignore.case = T,
  #     perl = T
  #   )
  #   
  # }
  
  text <-
    gsub(
      pattern = "\\sand\\s(\\w*$)",
      replacement = ",\\1",
      ignore.case = T,
      text
    )   ##Replaces and with ,(comma) if the pattern is ' word and word[end]'
  text <-
    gsub(
      pattern = "\\sand\\s(\\w*\\.$)",
      replacement = ",\\1",
      ignore.case = T,
      text
    )##Replaces and with ,(comma) if the pattern is ' word and word.[end]'
  
  text <-
    paste0(text, ifelse(grepl(pattern = "\\.$", x = text), "", "."), sep = "")  ###Adds a "." at the end of the description of each food
  text <- gsub("\\.|;", ",", text)
  
  ingd0_prep <- prepare_text(text)
  
  ### Fails List: if the number of opening and closing brackets don't match add it to fails_list
  # if (sum(braces[names(ingd0_prep)], neg_braces[names(ingd0_prep)], na.rm = T) != 0) {
  #   failed_ean_list <- c(failed_ean_list, ean_no)
  # }
  
  sub_ingred <-
    gregexpr(pattern = club_ingred,
             text = text,
             ignore.case = T)
  
  if (sub_ingred[[1]][1] != -1) {
    ##A match is found
    text <-
      gsub(
        text,
        pattern = club_ingred,
        replacement = "",
        ignore.case = T
      )
    #print("found_it")
    #browser()
    p = 0
    for (sub_ingreds in 1:length(sub_ingred[[1]])) {
      matched = sub_ingred[[1]][sub_ingreds] + attr(sub_ingred[[1]], 'match.length')[sub_ingreds] + p
      
      ingd0_prep <- ingd0_prep[-match(matched - 1, ingd0_prep)]
      ingd0_prep[which(ingd0_prep > matched)] <-
        ingd0_prep[which(ingd0_prep > matched)] - attr(sub_ingred[[1]], 'match.length')[sub_ingreds]
      p = p - attr(sub_ingred[[1]], 'match.length')[sub_ingreds]
    }
    
  }
  
  k = 1
  i = 1
  without_brackets <- list()
  with_brackets <- list()
  while (i <= length(ingd0_prep)) {
    if (!names(ingd0_prep)[i] %in% names(braces)) {
      ##the ingredients are not within parenthesis
      #print(text)
      without_brackets <-
        append(without_brackets,
               substr(text, k, ingd0_prep[i] - 1) %>%
                 #trimws() %>%
                 tolower())
      
    }
    
    
    else if (names(ingd0_prep)[i] %in% names(braces)) {
      #browser()
      ##New changes 12/30
      outside_braces1 <-
        substr(text, k, ingd0_prep[i] - 1) #%>% trimws() %>%  tolower()
      outside_braces <- outside_braces1
      len_out_braces <- nchar(outside_braces)
      ##Replacing ingredients outside brackets
      # for(ing_repl in 1:nrow(ingred_replacements)){
      #     #print(outside_braces)
      #     outside_braces <- gsub(pattern = as.character(ingred_replacements$Ingredient[ing_repl]),
      #                            replacement = as.character(ingred_replacements$Replacement[ing_repl]), outside_braces, ignore.case = T)
      #
      # }
      #browser()
      outside_braces <-
        gsub("\\.|;", ",", outside_braces)     ##Changed: commented on 5/28/2020
      outside_braces <- gsub("\\*|\\*\\*", "", outside_braces)
      outside_braces1 <- gsub("\\*|\\*\\*", "", outside_braces1)
      outside_braces1 <- gsub("\\+|\\+\\+", "", outside_braces1)
      outside_braces <- gsub("\\+|\\+\\+", "", outside_braces)
      outside_braces <-
        gsub(
          comma_replacements,
          replacement = ",",
          outside_braces,
          ignore.case = T
        )
      ##New K is the last comma in outside_braces + 1
      #print(nchar(outside_braces))
      #substr(text, k, ingd0_prep[i] - 1) <- paste(outside_braces, paste0(collapse = "", rep(" ",abs(len_out_braces - nchar(outside_braces)))))
      #replacement <- paste(outside_braces, paste0(collapse = "", rep(" ",abs(len_out_braces - nchar(outside_braces)))))
      #print(ean_no)
      text <-
        sub(pattern = outside_braces1, replacement = outside_braces, text)
      last_comma <-
        gregexpr(pattern = ",", outside_braces)[[1]][length(gregexpr(pattern = ",", outside_braces)[[1]])]
      k <- sum(c(k, last_comma), na.rm = T)
      without_brackets <-
        append(without_brackets,
               substr(outside_braces, 0, last_comma - 1))
      #print(ean_no)
      ##End of new change 12/30
      #browser()
      ##Commented on 07_17_2020
      # counter <- braces[names(ingd0_prep)[i]]
      #
      # while(counter != 0){   ##run loop till matching bracket found
      #
      #     i= i+1
      #     counter <- sum(braces[names(ingd0_prep)[i]],neg_braces[names(ingd0_prep)[i]], counter, na.rm = T)
      #     if(i > length(ingd0_prep)) {
      #         #fails_list <- c(fails_list, ean_no)
      #         break()
      #     }
      #
      # }
      # ##Added 06_18_2020 for handling ingredients of pattern "text (text1, text2) text3,"
      # if (names(ingd0_prep)[i] != ","& !is.na(names(ingd0_prep)[i]) & names(ingd0_prep)[i] != "("){
      #     i = i+1
      # }
      ##End of Comments 07_17_2020
      ##New Changes 07_17_2020
      #browser()
      while (i <= length(ingd0_prep) & names(ingd0_prep[i]) != ",") {
        if (names(ingd0_prep[i]) == "(") {
          counter2 <- braces[names(ingd0_prep)[i]]
          while (counter2 != 0) {
            ##run loop till matching bracket found
            i = i + 1
            counter2 <-
              sum(braces[names(ingd0_prep)[i]], neg_braces[names(ingd0_prep)[i]], counter2, na.rm = T)
            if (i > length(ingd0_prep)) {
              #fails_list <- c(fails_list, ean_no)
              break()
            }
          }
        }
        i = i + 1
      }
      ##End of New Changes
      ##End of addition
      ##Added 1/6/2020 - to remove extra spaces being put into the with_brackets terms
      #browser()
      ingd0_prep <-
        ingd0_prep + (nchar(outside_braces) - nchar(outside_braces1))
      with_brackets <-
        append(
          with_brackets,
          substr(text, k, ingd0_prep[i] - 1) %>% gsub(pattern = "\\s{2,}", replacement = " ") %>% trimws() %>% tolower()
        )
      ##with_brackets <- append(with_brackets, substr(text, k, ingd0_prep[i]) %>% trimws() %>% tolower()) ##Original code
      ##End of addition
      
    } else if (names(ingd0_prep)[i] %in% names(neg_braces)) {
      names(ingd0_prep[i]) <- ","
      substr(text, ingd0_prep[i], ingd0_prep[i]) <- ","
    }
    k = ingd0_prep[i] + 1
    i = i + 1
  }
  #browser()
  without_brackets <-
    paste0(na.omit(without_brackets), collapse = ",")
  #print(without_brackets)
  # for(ing_repl in 1:nrow(ingred_replacements)){
  #     #browser()
  #     #print(without_brackets)
  #     without_brackets <- gsub(pattern = as.character(ingred_replacements$Ingredient[ing_repl]),
  #                              replacement = as.character(ingred_replacements$Replacement[ing_repl]), without_brackets, ignore.case = T)
  #
  # }
  #browser()
  without_brackets <-
    gsub("\\.|;", ",", without_brackets)    ##Changed: removed ":" on 5/28/2020
  without_brackets <-
    gsub(
      comma_replacements,
      replacement = ",",
      without_brackets,
      ignore.case = T
    )
  #without_brackets <- gsub(pattern = "'and'", replacement = 'and', without_brackets, ignore.case = T)
  with_brackets <- paste0(na.omit(with_brackets), collapse = ",")
  #with_brackets <- gsub(pattern = "'and'", replacement = 'and', with_brackets, ignore.case = T)
  text <- paste(without_brackets, with_brackets, sep = ",")
  text <-
    paste0(text, ifelse(grepl(pattern = "\\.$", x = text), "", "."), sep = "")  ###Adds a "." at the end of the description of each food
  text <-
    gsub("\\.|;", ",", text)  ##Changed: removed ":" on 5/28/2020
  #browser()
  
  #browser()
  text <-
    gsub(
      pattern = "'and'",
      replacement = 'and',
      text,
      ignore.case = T
    )
  text <-
    gsub(
      pattern = "'&'",
      replacement = '&',
      text,
      ignore.case = T
    )
  text <-
    gsub(
      pattern = "'and/or'",
      replacement = 'and/or',
      text,
      ignore.case = T
    )
  text <- gsub(pattern = ",{2,}", replacement = ",", text)
  text <- gsub("\\*|\\*\\*", "", text)
  text <- gsub("\\+|\\+\\+", "", text)
  #print(text)
  rm(without_brackets)
  rm(with_brackets)
  #text <- gsub(comma_replacements, replacement = ",", text, ignore.case = T)
  
  #print(text)
  ingd1_prep <- prepare_text(text)
  #browser()
  
  func2_output <-
    ingid_list_prep(brackets = ingd1_prep,
                    ingrid_values = text,
                    braces,
                    neg_braces,
                    ean_no)
  rm(text)
  list_ingid <- func2_output$list_of_ingrids
  #failed_ean_list <- failed_ean_list  ##Gets the list of EANs that failed from func2
  
  #final_list <- bind_rows(final_list, list_ingid)
  
  return(list_ingid)
  #abort(print(ean_no))
}
```

```{r}
sampleDf <- readxl::read_xlsx("inputFiles/cookie_sample2_12_2.xlsx")
```

```{r}
serialOp <- apply(sampleDf[,2], 1, func_ingredTransform) %>% bind_rows() %>% as.data.frame()
## Works Fine
```

```{r}
serialOp %>% View()
```

## Parallelized op
```{r}

cl <- makeCluster(3)#, type = "PSOCK")

clusterExport(cl, list("prepare_text", "str_length", "%<>%", "club_ingred", "%>%", "comma_replacements", "ingid_list_prep"))

parallelOp <- parApply(cl, sampleDf[,2], 1, func_ingredTransform) %>% bind_rows() %>% as.data.frame()
stopCluster(cl)
```

```{r}
microbenchmark(
  apply(sampleDf[,2], 1, func_ingredTransform) %>% bind_rows() %>% as.data.frame(),
  parApply(cl, sampleDf[,2], 1, func_ingredTransform) %>% bind_rows() %>% as.data.frame()
)
```





